export const characters = [
  {
    value: null,
    label: "All",
  },
  {
    value: "pear",
    label: "Pear",
  },
  {
    value: "cherry",
    label: "Cherry",
  },
  {
    value: "watermelon",
    label: "Watermelon",
  },
  {
    value: "fig",
    label: "Fig",
  },
  {
    value: "pineapple",
    label: "Pineapple",
  },
  {
    value: "blueberry",
    label: "Blueberry",
  },
];
export const backs = [
  { value: null, label: "All" },
  { value: "red", label: "Red" },
  { value: "navy", label: "Navy" },
  { value: "blue", label: "Blue" },
  { value: "fig", label: "Fig" },
  { value: "yellow", label: "Yellow" },
  { value: "orange", label: "Orange" },
];
export const rarities = [
  { value: null, label: "All" },
  { value: "common", label: "Common" },
  { value: "uncommon", label: "Uncommon" },
  { value: "rare", label: "Rare" },
  { value: "ultraRare", label: "Ultra Rare" },
];
export const sortBy = [
  { value: null, label: "new first" },
  {
    value: "rarity",
    label: "rarity",
  },
];
export const slidesPerView = [
  { value: { inRow: 5, rows: 5 }, label: 25 },
  { value: { inRow: 10, rows: 5 }, label: 50 },
  { value: { inRow: 10, rows: 10 }, label: 100 },
];
export const slides = [
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple #8",
  },
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple #8",
  },
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple",
  },
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple #8",
  },
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple",
  },
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple #8",
  },
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple #8",
  },
  {
    imgSrc: "assets/nfts/1.png",
    rarity: "common",
    background: "red",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/2.png",
    rarity: "uncommon",
    background: "green",
    character: "watermelon",
  },
  {
    imgSrc: "assets/nfts/3.png",
    rarity: "rare",
    background: "navy",
    character: "blueberry",
  },
  {
    imgSrc: "assets/nfts/4.png",
    rarity: "ultraRare",
    background: "orange",
    character: "pear",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple",
  },
  {
    imgSrc: "assets/nfts/5.png",
    rarity: "common",
    background: "fig",
    character: "fig",
  },
  {
    imgSrc: "assets/nfts/6.png",
    rarity: "uncommon",
    background: "red",
    character: "garnet",
  },
  {
    imgSrc: "assets/nfts/7.png",
    rarity: "rare",
    background: "yellow",
    character: "cherry",
  },
  {
    imgSrc: "assets/nfts/8.png",
    rarity: "ultraRare",
    background: "blue",
    character: "pineapple",
  },
];
